github:
  is_project_page: false

title: "Alexander Berditschewski"

description: >
  Bewerbung Informatiker EFZ Applikationsentwicklung &
  Entwickler Digitales Business |
  Digitale Bewerbungsmappe

url: "https://alexanderberditschewski-pixel.github.io"
baseurl: "/alexander_berditschewski"

theme: jekyll-theme-cayman

lang: de-CH
timezone: Europe/Zurich

author:
  name: "Alexander Berditschewski"
  email: "alexander.berditschewski@gmail.com"

github_username: "alexanderberditschewski-pixel"

# Navigation
header_pages:
  - index.md
  - about-me.md
  - cv.md
  - education.md
  - it-knowledge.md
  - projects.md
  - experience.md
  - strengths.md
  - sports.md
  - languages.md
  - interests.md
  - references.md
  - contact.md
  - downloads.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

show_downloads: false

# SEO
tagline: "Digitale Bewerbungsmappe"

logo: "/assets/images/profile.jpg"

social:
  name: "Alexander Berditschewski"
  links:
    - https://github.com/alexanderberditschewski-pixel

# Standardbild für Social Preview
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/images/profile.jpg"

# Dateien, die nicht veröffentlicht werden sollen
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Kramdown Optionen
kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink: pretty

# Optional für spätere Projekte
collections:
  projects:
    output: true
