title: "Alexander Berditschewski"
description: "Portfolio | Informatik | Digital Business | Projekte"

url: "https://alexanderberditschewski-pixel.github.io"
baseurl: "/alexander_berditschewski"

theme: jekyll-theme-cayman

lang: de-CH
timezone: Europe/Zurich

author:
name: "Alexander Berditschewski"
email: "[alexander.berditschewski@gmail.com](mailto:alexander.berditschewski@gmail.com)"

github_username: "alexanderberditschewski-pixel"

header_pages:

* cv.md
* projects.md
* certificates.md
* contact.md
* about-me.md

plugins:

* jekyll-feed
* jekyll-seo-tag

markdown: kramdown
highlighter: rouge

show_downloads: false

exclude:

* README.md
* Gemfile
* Gemfile.lock
* node_modules
* vendor
